- src/main/java/com/cheocharm/MapZ/MapZApplication.java
- src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
- src/main/java/com/cheocharm/MapZ/common/BaseEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/InvitationStatus.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserRole.java
https://www.erdcloud.com/d/argY2FZcL5uNrpyo8
위 링크를 바탕으로 만들어졌습니다 ^^
> feat: erd 설계 구현

- src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/domain/BaseEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
- BaseEntity  패키지 위치 재설정
- Spring securit Config 임시 설정 (차후에 추가 설정 예정)
> feat: Spring security Config 임시 설정

- build.gradle
querydsl 설정했습니다.
컴파일 해보니 잘 작동하네요~
> feat: querydsl 설정

- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
@ManyToOne 필드에 @JoinColumn으로 전부 변경했고
email, username, groupname에 unique 붙여줬습니다 ~
로컬에 DB 만들어지는거 확인!
> hotfix: @JoinColumn 어노테이션 추가 및 unique 활성화

- src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
>
* @AttributeOverride 애너테이션 삭제
* 테이블명 수정
* 컬럼명 member_id -> user_id 수정
> hotfix: @AttributeOverride 삭제 및 테이블, 컬럼명 수정

- build.gradle
- src/main/java/com/cheocharm/MapZ/common/config/AuthenticationEntryPointCustom.java
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationFilter.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationUtils.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCommonUtils.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
- JWT 토큰 발행 구현
- JWT 인증 필터 구현
- JWT 리프레쉬 토큰을 위한 userRepository 추가
> feat: JWT 토큰 발행 기능 구현 및 시큐리티 필터 추가

- src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
- src/main/resources/logback-spring.xml
- 데이터 유무에 대한 success 메서드 구현
- 예외나 잘못된 요청에 대한 fail 메서드 구현
- 토큰 만료에 대한 Expire 메서드 구현
> feat: Common Response 구현

- src/main/java/com/cheocharm/MapZ/common/interceptor/AuthInterceptor.java
- src/main/java/com/cheocharm/MapZ/common/interceptor/UserThreadLocal.java
- UserThreadLocal 구현을 통해 서비스 코드에서 이용하도록 구현
-  Interceptor를 이용하여 UserEntity get, set, remove 할 수 있도록 구현
> feat: ThreadLocal 구현

- src/main/java/com/cheocharm/MapZ/common/exception/CustomException.java
- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
* 로그용 코드, 프론트 리스폰스용 코드, 메세지 리턴하는 CustomException 구현
* CustomException 작성할 ExceptionDetails 구현
* ExceptionHandler 구현
> feat: ExceptionHandling 구현

- src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
- src/main/java/com/cheocharm/MapZ/common/interceptor/AuthInterceptor.java
AuthInterceptor 등록 후 적용할 path 유동적으로 변경 예정
> feat: AuthInterceptor 등록

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
ExceptionDetails에 있는 enum 수정했습니다 ~
> fix: ExceptionDetails에서 오류 type 제거

- build.gradle
- src/main/java/com/cheocharm/MapZ/MapZApplication.java
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
- src/main/java/com/cheocharm/MapZ/common/oauth/GoogleYml.java
- src/main/java/com/cheocharm/MapZ/common/oauth/OauthApi.java
- src/main/java/com/cheocharm/MapZ/common/oauth/OauthUrl.java
- src/main/java/com/cheocharm/MapZ/common/util/ObjectMapperUtils.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/GoogleIdTokenDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/TokenPairResponseDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/UserLoginDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/UserSignUpDto.java
-  구글 yml 값 관련 기능 구현
-  구글 로그인 기능 구현
-  ObjectMapper util 클래스 추가
-  AuthInterceptor  excludePathPatterns 추가
-  SecurityConfig 로그인 시에 403걸리지 않게 임시로 수정(차후 API 마다 권한 검증하도록 변경)
> feat: 구글 로그인 구현

- src/main/java/com/cheocharm/MapZ/MapZApplication.java
- src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/FailConvertException.java
- src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
- src/main/java/com/cheocharm/MapZ/common/exception/InternalServerException.java
- src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
- src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogAspect.java
- src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogSchema.java
- src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogAspect.java
- src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogSchema.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
* AspectJ 사용하여 로그 구현 (Response, Exception)
* Diary, Group Controller 파일 생성 (ResponseLogAspect 구현을 위해 파일만 미리 생성)
* Exception 추가
* GlobalExceptonHandler 수정 (매개변수 삭제)
* Common Response 수정 (success 메서드에 custom code 추가)
* 띄어쓰기 수정
ERROR - Exception 로그
INFO - Response 로그
> feat: 로그 구현

- Dockerfile
- deploy.sh
> feat: 배포를 위해 Dockerfile 및 shell script 작성

- build.gradle
- src/main/java/com/cheocharm/MapZ/common/config/S3Config.java
- src/main/java/com/cheocharm/MapZ/common/util/S3Service.java
- src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
그룹 이미지 올릴 때 S3Service에 있는 uploadGroupImage 사용하시면 됩니다 ~
group 이름은 중복될 수 있어서 groupUUID로 사진 저장명 설정했습니다!
슬랙에 있는 yml 파일을 다운받아주세요 ~
> feat: S3 설정

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/S3/FailConvertToFileException.java
- src/main/java/com/cheocharm/MapZ/common/exception/S3/FailDeleteFileException.java
> feat: S3 예외 설정

- src/main/java/com/cheocharm/MapZ/common/config/JpaAuditConfig.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GroupListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepository.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepository.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
그룹 생성, 조회 기능을 구현했는데
이미지 업로드 기능은 유저 프로필 업로드 변경하면서 같이 진행할 예정입니다.
> feat: 그룹 생성, 조회 기능 구현

- build.gradle
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
- src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
- src/main/java/com/cheocharm/MapZ/common/exception/common/FailConvertToJsonException.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/DuplicatedEmailException.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/DuplicatedUsernameException.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/InvalidJwtException.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/NotFoundUserException.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/WrongPasswordException.java
- src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogSchema.java
- src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogSchema.java
- src/main/java/com/cheocharm/MapZ/common/util/RandomUtils.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckEmailPasswordDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignInDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignUpDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
* 회원가입
닉네임 중복 체크
* 로그인
* 이메일, 비밀번호 유효성 체크
실제 사용하는 이메일인지 확인(google SMTP)
테스트코드 추후 구현
슬랙에 업데이트된 yml 파일을 다운받아주세요!
> feat: 맵지 회원가입/로그인

- build.gradle
- deploy.sh
- nonstop.sh
> feat: nginx 설정 및 배포스크립트 작성

- nonstop.sh
> fix 배포 스크립트 수정

- src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
- src/main/java/com/cheocharm/MapZ/agreement/repository/AgreementRepository.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/GoogleSignUpDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignUpDto.java
* 회원가입 하면 자동으로 정보 제공 동의
* 푸시알림은 사용자에 따라 다르게 전달 받음
> feat: 정보 제공 동의 기능 구현

- .gitignore
- .travis.yml
* travis CI yml 파일 작성
* .gitignore 파일 수정
> feat: Travis CI 설정 파일 작성

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/usergroup/NotFoundUserGroupException.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeInvitationStatusDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/JoinGroupDto.java
- src/main/java/com/cheocharm/MapZ/usergroup/InvitationStatus.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepository.java
개발한 것
- 그룹 가입 신청
- 그룹 가입 신청상태 그룹장이 수락 or 거절
GroupService 코드가 상당한 냄새를 품기고 있는데 일단 머리에 떠오르는게 없네요(데이터베이스 설계 문제인거 같기도 하고,,)
> feat: 그룹 가입 신청 및 그룹 가입 신청상태 변경 API 구현

- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
- 그룹생성 시 공백허용해서 생성할 수 있도록 변경
- 의도한건지 모르겠지만 이미지 파일 null로 보내면 isEmpty()는 NullPointerException 발생해서 
다음과 같이 변경
> feat: 그룹생성 정규식 추가

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/user/ExitGroupChiefException.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepository.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ExitGroupDto.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
현재로는 삭제해야할 엔티티는 이정도인데
향후 댓글이나 좋아요 기능 생기면 추가 작성해야 할것 같습니다~
> feat: 그룹 나가기 API

- src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationUtils.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCommonUtils.java
- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserProvider.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
JWT에 회원가입 제공자 정보 추가
이에 따라 이메일이나, 비밀번호 찾기 시 구글가입이랑 겹치지 않음
그리고 이미지 업로드 메서드들 파일 검증 방식 롤백 했습니다...
> feat: 회원가입 경로(제공자) 필드 추가

- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeChiefDto.java
- src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
> feat: 그룹장 변경 API

- src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
- src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/GetUserListDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
유저 검색시 자신은 데이터에 포함되지 않도록 하기 위해 JWT를 받습니다.
이에 따라 Interceptor Uri 변경이 이뤄졌습니다.
> feat: 유저 검색 페이징

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/FailConvertException.java
- src/main/java/com/cheocharm/MapZ/common/exception/diary/AlreadyLikedDiaryException.java
- src/main/java/com/cheocharm/MapZ/common/exception/diary/NotFoundDiaryException.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/LikeDiaryDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepository.java
다이어리 좋아요 API 기능 개발하였습니다 ~ !
빌드 해봤는데 잘 되는 것 까지 확인!
> feat: 다이어리 좋아요 API

- src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
refreshToken으로 accessToken 발급시 
새로 생성된 refreshToken으로 교체
> feat: refreshToken으로 accessToken 발급

- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/InviteUserListDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
유저 닉네임과 그룹명을 활용해서 그룹에 초대하여 저장합니다.
다만 그룹 초대시에 이미 가입되어 있는 유저나 초대되어 있는 유저는 어떻게 해야할지 프론트랑 얘기가 필요...
> feat: 유저 그룹 초대 API

- src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
> feat: 그룹 조회 정보 추가

- src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
> fix: refreshToken을 통해 JWT 재발급하는 API 

- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
swagger에 response가 정확히 나오지 않아 타입 명시하는 것으로 수정
> docs: swagger 수정

- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/GetUserListDto.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
그룹 멤버인지 판단하는 코드입니다.
Dto에 그룹 멤버면 member 필드가 true 아니면 false
> feat: 그룹 초대를 위한 유저 검색시 그룹 멤버 판단

- src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepository.java
- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
그룹조회시 제목처럼 수정했고,
그룹 조회 로직이 잘못된 로직이라서 새로 바꿨습니다. 
성능 관련해서 노션 투두에 작성했는데 나중에 기능개발  끝나면 하는걸로..
> feat: 그룹 조회시  검색허용 가능한 그룹만 조회

- src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/PagingGetGroupListDto.java
글쓰기전 글을 작성할 그룹 선택할때 필요한 API 입니다~
> feat: 유저가 속한 그룹 찾기 API

- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/dto/MyPageInfoDto.java
닉네임이랑 프로필이밎 받을 수 있도록 작성
null로 오는 경우 기본이미지 사용하도록 설계
> feat: 마이페이지 정보 API

- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/PagingGetGroupListDto.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/vo/ChiefUserImageVO.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/vo/CountUserGroupVO.java
그룹 검색이랑, 속해 있는 그룹 검색할때 유저수 찾기랑, 그룹별 그룹장 이미지 획득할때 
발생하는 N+1 문제 수정했습니다~
> fix: 그룹 검색 관련 기능 N+1 수정

- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeChiefDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeGroupStatusDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeInvitationStatusDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/ExitGroupDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/InviteUserListDto.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/JoinGroupDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
멤버관리 페이지 API 만들때 유저 id도 제공해야겠네요
> feat: 그룹 아이디, 유저아이디로 데이터 조회 및 로직 수정

- src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/GroupMemberDto.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
- src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
그룹 멤버수 찾을때 아직 대기중인 멤버도 조회하는 버그 수정했습니다~
> feat: 그룹 멤버조회 API userId 필드 추가, refactor: UserGroupEntity 조회 로직 개선

- src/main/java/com/cheocharm/MapZ/comment/domain/CommentController.java
- src/main/java/com/cheocharm/MapZ/comment/domain/CommentEntity.java
- src/main/java/com/cheocharm/MapZ/comment/domain/CommentService.java
- src/main/java/com/cheocharm/MapZ/comment/domain/dto/CreateCommentDto.java
- src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepository.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- 유투브, 인스타그램 댓글 형식
- 원본(부모) 댓글이 있고 그 밑에 댓글들을 달 수 있음
- 무한 댓글X
- 댓글은 수정할 수 없음
- 게시글이 삭제되면 댓글도 삭제되고, 대댓글도 삭제된다.
- 댓글이 삭제되면, 대댓글도 삭제된다.
이렇게 기능 개발하려고 합니다! 논의할 부분 있다면 웰컴👀
> Feat: 댓글 작성

- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustom.java
- src/test/java/com/cheocharm/MapZ/IntegrationTest.java
- src/test/java/com/cheocharm/MapZ/RepositoryTest.java
- src/test/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustomImplTest.java
- src/test/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImplTest.java
- src/test/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImplTest.java
Data JPA 메서드나, 단순히 ID 기반으로 찾는 메서드는 테스트 코드를 작성하지 않았습니다~
더 좋은 코드 짤 수 있는 방법 공유받습니다..
> test: Repository 클래스 테스트 코드 작성

- build.gradle
- src/main/java/com/cheocharm/MapZ/common/config/AuthenticationEntryPointCustom.java
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/GetDiaryListDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/WriteDiaryDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
API 구현별로 Security Config에 작성해줘야 합니다~
일기 작성 및 조회는 프론트에서 S3랑 기획관련해서 조금 더 얘기해봐야 할거 같아서
매우 러프하게 짜놨으니 감안해주세요!
> feat: Security Config 수정, 일기 작성 및 조회

- src/main/java/com/cheocharm/MapZ/comment/domain/CommentController.java
- src/main/java/com/cheocharm/MapZ/comment/domain/CommentEntity.java
- src/main/java/com/cheocharm/MapZ/comment/domain/CommentService.java
- src/main/java/com/cheocharm/MapZ/comment/domain/dto/DeleteCommentDto.java
- src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepository.java
> Feat: 댓글 삭제

- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/test/java/com/cheocharm/MapZ/RepositoryTest.java
배포시 Spring Actuator 사용할때 인증에 걸리지 않도록 수정했습니다~
> hotfix: Spring Actuator 요청 인증

- pull.sh
- src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
Jenkins에서 빌드 후 Docker Hub에서 Image Pull한 후 무중단 배포 스크립트 실행하는 방식을 사용
단계를 더 단축시킬 수 있을거 같은데 생각해봐야 할듯...
> feat: 도커 이미지 Pull 스크립트, 그룹 소개글 글자수 제한

- pull.sh
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/DeleteDiaryDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/DiaryLikePeopleDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepository.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
일기 삭제 할때 댓글 모두 삭제하도록 적용했습니다.
그리고 좋아요 누른 일기도 좋아요 일기목록에서 삭제되어야 한다고 생각해서 DiaryLikeEntity에도 Cascade 걸었네요
> feat: 일기 좋아요 누른 명단 조회 및 일기 삭제 API

- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
- src/main/java/com/cheocharm/MapZ/common/util/QuerydslSupport.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/MyDiaryDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/dto/MyLikeDiaryDto.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/vo/MyDiaryVO.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/vo/MyLikeDiaryVO.java
QueryDSL 메서드에서 comment count() 서브쿼리 안쓰고 
Comment없는 diary는 0으로 출력되기 위해 leftJoin사용했습니다~ 
QueryDSL 쓸수록 어렵네요..
> feat: 내가 쓴 일기 및 좋아요한 일기 조회 API

- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/report/AlreadyReportedDiary.java
- src/main/java/com/cheocharm/MapZ/report/domain/ReportController.java
- src/main/java/com/cheocharm/MapZ/report/domain/ReportEntity.java
- src/main/java/com/cheocharm/MapZ/report/domain/ReportService.java
- src/main/java/com/cheocharm/MapZ/report/domain/dto/ReportDto.java
- src/main/java/com/cheocharm/MapZ/report/domain/repository/ReportRepository.java
- 중복 신고 방지
- 3번 이상 신고 시 게시글 삭제
3번 이상 신고당하면 게시글 삭제되도록 했는데
Report 테이블에 신고 내역도 같이 삭제하도록 할까요?
> feat: 게시글 신고 기능

- src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
로컬에 이미지 저장한 후에 이를 활용하여 s3에 업로드하던 로직을 바로 업로드하는것으로 변경했습니다~
s3Utils 클래스 보면 상당히 리팩터링 마려운데 
일단 바로 배포후 급한 일정끝나는대로 다시 수정하겠습니다!
> fix: s3 업로드 로직 변경

- src/main/java/com/cheocharm/MapZ/diary/application/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/controller/DiaryController.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/dto/response/WriteDiaryResponse.java
db에 데이터 저장하도록 Columndefinition 설정하였습니다.
etc)
일기 작성 후 바로 해당일기로 가도록 Response를 추가하였습니다.
> fix: DB html 저장

- src/main/java/com/cheocharm/MapZ/comment/application/CommentService.java
- src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/comment/domain/repository/vo/CommentVO.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/controller/CommentController.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/request/CreateCommentRequest.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/request/DeleteCommentRequest.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/response/GetCommentResponse.java
- src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
- src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
- src/main/java/com/cheocharm/MapZ/report/application/ReportService.java
댓글 조회 기능 만들었습니다~
댓글 데이터 20개 넘게 넣어서 테스트해봤는데 잘되더라구요?
리개님 코드 잘 참고했습니다 님은최고입니다...🥺
> feat: 댓글 조회

- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
MySQL 버전업하면서 예약어 문제 떄문에 수정합니다!
> hotfix: 테이블명 수정

- src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
- src/main/java/com/cheocharm/MapZ/common/exception/usergroup/GroupMemberSizeExceedException.java
- src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
- src/main/java/com/cheocharm/MapZ/diary/application/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryImageRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryImageRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/dto/response/WriteDiaryImageResponse.java
- src/main/java/com/cheocharm/MapZ/group/application/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupConst.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupLimit.java
- src/main/java/com/cheocharm/MapZ/group/presentation/controller/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/AcceptInvitationRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/RefuseInvitationRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/response/MyInvitationResponse.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/repository/UserGroupRepository.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/repository/UserGroupRepositoryCustom.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/repository/UserGroupRepositoryCustomImpl.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/repository/vo/MyInvitationVO.java
GroupConst 클래스명이나 필드명이 좀 거슬리는점 빼곤 문제 없는거 같습니다~
> feat: 초대장 수락, 거절, 조회 API

- build.gradle
- src/main/java/com/cheocharm/MapZ/common/interceptor/UserThreadLocal.java
- src/main/java/com/cheocharm/MapZ/group/application/GroupService.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
- src/main/java/com/cheocharm/MapZ/group/domain/GroupLimit.java
- src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepository.java
- src/main/java/com/cheocharm/MapZ/group/presentation/controller/GroupController.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/AcceptInvitationRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/ChangeChiefRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/CreateGroupRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/ExitGroupRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/InviteGroupRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/JoinGroupRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/KickUserRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/RefuseInvitationRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/UpdateGroupRequest.java
- src/main/java/com/cheocharm/MapZ/group/presentation/dto/request/UpdateInvitationStatusRequest.java
- src/main/java/com/cheocharm/MapZ/user/presentation/dto/request/GoogleSignUpRequest.java
- src/main/java/com/cheocharm/MapZ/user/presentation/dto/request/MapZSignUpRequest.java
- src/main/java/com/cheocharm/MapZ/user/presentation/dto/response/TokenPairResponse.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/UserGroupEntity.java
- src/test/java/com/cheocharm/MapZ/ServiceTest.java
- src/test/java/com/cheocharm/MapZ/group/application/GroupServiceTest.java
- src/test/java/com/cheocharm/MapZ/user/application/UserServiceTest.java
> test: UserService, GroupService 테스트 코드

- src/main/java/com/cheocharm/MapZ/agreement/Agreement.java
- src/main/java/com/cheocharm/MapZ/comment/application/CommentService.java
- src/main/java/com/cheocharm/MapZ/comment/domain/Comment.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/request/CreateCommentRequest.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/request/DeleteCommentRequest.java
- src/main/java/com/cheocharm/MapZ/comment/presentation/dto/response/GetCommentResponse.java
- src/main/java/com/cheocharm/MapZ/common/domain/BaseEntity.java
- src/main/java/com/cheocharm/MapZ/diary/application/DiaryService.java
- src/main/java/com/cheocharm/MapZ/diary/domain/Diary.java
- src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImage.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/dto/request/DeleteTempDiaryRequest.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/dto/request/WriteDiaryImageRequest.java
- src/main/java/com/cheocharm/MapZ/diary/presentation/dto/request/WriteDiaryRequest.java
- src/main/java/com/cheocharm/MapZ/group/domain/Group.java
- src/main/java/com/cheocharm/MapZ/like/application/LikeService.java
- src/main/java/com/cheocharm/MapZ/like/domain/DiaryLike.java
- src/main/java/com/cheocharm/MapZ/like/presentation/dto/request/LikeDiaryRequest.java
- src/main/java/com/cheocharm/MapZ/like/presentation/dto/response/DiaryLikePeopleResponse.java
- src/main/java/com/cheocharm/MapZ/report/application/ReportService.java
- src/main/java/com/cheocharm/MapZ/report/domain/Report.java
- src/main/java/com/cheocharm/MapZ/report/domain/repository/ReportRepository.java
- src/main/java/com/cheocharm/MapZ/report/presentation/dto/ReportRequest.java
- src/main/java/com/cheocharm/MapZ/user/application/UserService.java
- src/main/java/com/cheocharm/MapZ/user/domain/User.java
- src/main/java/com/cheocharm/MapZ/usergroup/domain/UserGroup.java
- src/test/java/com/cheocharm/MapZ/ServiceTest.java
- src/test/java/com/cheocharm/MapZ/comment/application/CommentServiceTest.java
- src/test/java/com/cheocharm/MapZ/diary/application/DiaryServiceTest.java
- src/test/java/com/cheocharm/MapZ/like/application/LikeServiceTest.java
- src/test/java/com/cheocharm/MapZ/report/application/ReportServiceTest.java
etc)
Report,Comment Service 메서드 추출
변수명 변경
> test: Service 클래스 테스트 코드 작성
